# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chuck Rock
email: chuck@rock.io
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: chuck-rock
github_username:  chuck-rock

# Build settings
markdown: kramdown

exclude: ["readme.md"]

permalink: blog/:year/:title/
relative_permalinks: false
